export enum MovieGenre {
  Action = 'Action',
  Adventure = 'Adventure',
  Animation = 'Animation',
  Comedy = 'Comedy',
  Crime = 'Crime',
  Documentary = 'Documentary',
  Drama = 'Drama',
  Fantasy = 'Fantasy',
  Historical = 'Historical',
  Horror = 'Horror',
  Musical = 'Musical',
  Mystery = 'Mystery',
  Romance = 'Romance',
  SciFi = 'Sci-Fi',
  Thriller = 'Thriller',
  War = 'War',
  Western = 'Western',
}
